version: "3"
services:
  ui:
    container_name: window_component
    image: node:9.11.1
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/usr/local/lib/node_modules
    entrypoint: bash -c "cd /app && npm i -g create-react-app && yarn install && yarn start"

volumes:
  node_modules:
    external: true